### ISSUE TITLE
Server owned chunks

### ISSUE THREAD

**Issue by LatvianModder** [FTBTeam/FTB-Chunks#1]
https://github.com/FTBTeam/FTB-Utilities/issues/88

**Comment by 2iguys** [comment]
Curious 1 year later from this, has the feature of chunk loading time expiration ever been re-implemented, or how far off could that potentially be, I know it was not a high priority issue, but it's been a while.

**Comment by liampearson96** [comment]
Is this Going to be implemented for mc version 1.15.2? And will IT be anytime soon? Thanks
