### ISSUE TITLE
[Suggestion][1.16.5]  Add Teleport to Waypoints

### ISSUE THREAD

**Issue by jayzone91** [FTBTeam/FTB-Chunks#102]
It would be nice if i could Teleport to my Waypoints in creative or as an Admin.

**Comment by MacAttack-UK** [comment]
I know you can teleport to a waypoint or anywhere on the map by hovering over it and pressing 't' but it only teleports you to the top and not underground if you set a waypoint there. I found your post whilst seeing if there was a way to teleport to the exact waypoint including y coords. Hopefully this will help you a little as I had the same issue.

**Comment by Akaitatsu** [comment]
Upvote
