### ISSUE TITLE
PLEASE add ability for admins to select specific chunks that NO ONE can claim!!! For Spawn Claiming!

### ISSUE THREAD

**Issue by societytime** [FTBTeam/FTB-Chunks#108]
i feel like if this could just be made to better suite a server admin in setting up a spawn that no one can claim and that allows people to use blocks like adventure mode but maybe disables pvp so that ppl can use shop! This would be soooooo coool please add i love this mod it is so easy to use. it could be made infinitely better by this suggestion though; ADMIN CHUNK CLAIMS :D

**Comment by societytime** [comment]
pls kids keep claiming my spawn X(

**Comment by goldern** [comment]
Can't you claim the land first? And unclaim with server commands if it's near the desired area?

**Comment by MaxNeedsSnacks** [comment]
You can already create a server team and claim spawn chunks for that team, so that noone else can claim it
