### ISSUE TITLE
[Minor bug, easy fix] Warpstone via Waystone mods not usable in claimed areas.

### ISSUE THREAD

**Issue by Cixon** [FTBTeam/FTB-Chunks#113]
**Context:** Using the [Waystones](https://www.curseforge.com/minecraft/mc-mods/waystones) mod, users cannot use their Warpstones to teleport anywhere in claimed areas they are not allied with. This has something to do with the interactive restrictions.

**Comment by MaxNeedsSnacks** [comment]
Should be fixed in the newest release, right-click actions are now much, much more permissive
