### ISSUE TITLE
Claimed Chunks can be forced by anyone

### ISSUE THREAD

**Issue by ShoRyuuga** [FTBTeam/FTB-Chunks#119]
Hey there,

I am not understanding this Mod at all. It allows everyone to claim chunks, despite being adventurer, survivalist etc. 
Can't the server operator decide who can temporary claim so he has an area. but generally noone can ?

And what does "forced loaded" mean ? Because yes when i force it, noone can work on my area, but they can just release the force loaded anytime by themselves...is this supposed to work like that because it makes this feature unnecessary.

Maybe someone can help me to understand this.

**Comment by MaxNeedsSnacks** [comment]
No, by default, everyone can claim chunks in FTB Chunks, if you want more granular control, use FTB Ranks (or other permission mods)
