### ISSUE TITLE
ClaimedChunkEvent.Claim never gets raised (ftb-chunks-1604.2.2.62)

### ISSUE THREAD

**Issue by AlienXAXS** [FTBTeam/FTB-Chunks#120]
Hi,
Before I continue I wanted to let you know that I am very new to Java and Forge Mods in general, and I may be missing something important that is causing the odd behavior listed below, if that is the case please let me know the correct approach to using the API.

Firstly please excuse me possibly being a bit dumb here, but I'm trying to use your FTB Chunks API and I noticed three things:

1. The 'Claim' event never seems to trigger
2. Instead of the 'Claim' event triggering, the 'Unclaim' event triggers when I claim a chunk
3. All triggers for 'Unclaim', 'Load', 'Unload' are fired twice upon a player claiming 1 chunk, if the player claims 2 chunks then 4 events are raised and so on - I can only assume this also would apply to the 'Claim' event.

I am using this code to test the APIs responses:
```java
@SubscribeEvent
	public static void onClaimEvent(final ClaimedChunkEvent raisedEvent)
	{		
		if ( raisedEvent instanceof ClaimedChunkEvent.Claim )
		{
			Plugin.LOGGER.info("We are an instance of ClaimedChunkEvent.Claim");
			//HandleClaimedChunkEvent(((Claim) raisedEvent));
		}
		
		if ( raisedEvent instanceof ClaimedChunkEvent.Unclaim )
		{
			Plugin.LOGGER.info("We are an instance of ClaimedChunkEvent.Unclaim");
			//HandleUnclaimChunkEvent(((Unclaim) raisedEvent));
		}
	}
	
	@SubscribeEvent
	public static void onClaimEventTwo(final ClaimedChunkEvent.Claim raisedEvent)
	{
		Plugin.LOGGER.info("############### ClaimedChunkEvent.Claim RAISED!");
	}
	
	@SubscribeEvent
	public static void onClaimEventTwo(final ClaimedChunkEvent.Unclaim raisedEvent)
	{
		Plugin.LOGGER.info("############### ClaimedChunkEvent.Unclaim RAISED!");
	}
	
	@SubscribeEvent
	public static void onClaimEventTwo(final ClaimedChunkEvent.Load raisedEvent)
	{
		Plugin.LOGGER.info("############### ClaimedChunkEvent.Load RAISED!");
	}
	
	@SubscribeEvent
	public static void onClaimEventTwo(final ClaimedChunkEvent.Unload raisedEvent)
	{
		Plugin.LOGGER.info("############### ClaimedChunkEvent.Unload RAISED!");
	}
```

Note:
Unclaim, Load and Unload all raise, including the instanceof checks in the initial method.

Am I doing something wrong here, or is the API broken for this state?

Many thanks.

**Comment by MaxNeedsSnacks** [comment]
This is definitely not intentional, and I've already prepared a fix for this, thanks for informing me this is an issue ^^

Do beware that FTB Chunks will be migrating to the Architectury API at some point in the future, so event behaviour may change!

**Comment by MaxNeedsSnacks** [comment]
Latest build should've fixed that ^^
