### ISSUE TITLE
Crash after update

### ISSUE THREAD

**Issue by kellixon** [FTBTeam/FTB-Chunks#122]
Crash after update FTBChunks 1605.2.3-67 (on the previous version 1604.2.2.63 everything works). 
log - https://gist.github.com/kellixon/2e08cec3eb42f5fa26b2c9db26bfeb10
crash-report - https://gist.github.com/kellixon/67aa87f2fc21653f04cde2bd84c14d91
![Безымянный](https://user-images.githubusercontent.com/22012731/110748892-6dbd0c80-8251-11eb-9ee5-ba5b16fc2ad7.jpg)

**Comment by MaxNeedsSnacks** [comment]
Please use build 68

**Comment by kellixon** [comment]
Still the game doesn't start.
