### ISSUE TITLE
Permission node to bypass chunk protection 

### ISSUE THREAD

**Issue by jinkhya** [FTBTeam/FTB-Chunks#124]
Hello!
Could it be possible to re implement a permission node to bypass chunk protection, so that we could give it to specific ranks with ftbessentials without having to OP players which defeats the purpose of ranks?
(It used to be possible with ftbutilities.claims.block.edit and ftbutilities.claims.block.interact)

Thanks!
Jin

**Comment by MaxNeedsSnacks** [comment]
Should also be possible now with https://github.com/FTBTeam/FTB-Chunks/commit/8c54615f02f1a335e159d34636f99ce69509fb41, just give people the permission to use that command

**Comment by jinkhya** [comment]
Awesome thanks!!
