### ISSUE TITLE
Player Game Crashing with Mixin Error

### ISSUE THREAD

**Issue by storiofmylife** [FTBTeam/FTB-Chunks#125]
FTB-Chunks: 1604.2.2.63
FTB-GUI_Lib: 1605.2.1.40
Forge: 36.0.45
Minecraft: 1.16.5

[Crash Report](https://pastebin.com/0m9WqhBL)

When one of our players tries to join server, it either causes the ftb chunks minimap not to load or it crashes her game completely.

**Comment by MaxNeedsSnacks** [comment]
Can you try to reproduce this with build 68?

**Comment by StormCircuit** [comment]
I am also having this issue with forge 36.0.27 however for me it crashes when I attempt to make a singleplayer world (not tested with SMP).

[crash report](https://pastebin.com/D6wa64hg)

**Comment by storiofmylife** [comment]
I tried installing build 68 onto my server and I'm now getting this crash. I did delete the old version before installing the update.
 
[Crash Report](https://pastebin.com/BpPstzNS)

**Comment by MaxNeedsSnacks** [comment]
Ah yes, it seems this is another entry in the well known book series "LatvianModder and the curious case of the unpushed bugfix"... fix should be rolling out soon, hopefully

**Comment by storiofmylife** [comment]
Thank you!!!

**Comment by StormCircuit** [comment]
I'm just a little unfamiliar with how to get it, it will show up on curseforge as an update, correct? Sorry for the slightly off-topic question.

**Comment by MaxNeedsSnacks** [comment]
It will, yeah. Gotta wait for Lat to push his fixes tho

**Comment by MaxNeedsSnacks** [comment]
Should be all good in build 69... nice
