### ISSUE TITLE
Keeps Causing Game to crash 

### ISSUE THREAD

**Issue by BHGHOST5257** [FTBTeam/FTB-Chunks#127]
Modpack: Direwolf20 1.16 - 1.7.0
Forge Version: 36.0.45
Mod Version: ftb-chunks-1605.2.3-
 
Hello,

When I remove a death point and try to exit the map it keeps causing my game to crashing, am I do something wrong or is it a bug. I've attached the last 3 crash reports below.

[crash-2021-03-05_13.40.55-client.txt](https://github.com/FTBTeam/FTB-Chunks/files/6146393/crash-2021-03-05_13.40.55-client.txt)
[crash-2021-03-08_14.01.58-client.txt](https://github.com/FTBTeam/FTB-Chunks/files/6146396/crash-2021-03-08_14.01.58-client.txt)
[crash-2021-03-08_14.06.10-client.txt](https://github.com/FTBTeam/FTB-Chunks/files/6146397/crash-2021-03-08_14.06.10-client.txt)

**Comment by MaxNeedsSnacks** [comment]
None of these are related to FTB Chunks; please contact the authors of Immersive Engineering and Astral Sorcery about these crashes instead.
