### ISSUE TITLE
cyclic Sack of Holding claim bypass [1.16.5]

### ISSUE THREAD

**Issue by ZWRh3** [FTBTeam/FTB-Chunks#128]
sack of holding can be used to pickup tile entities from claimed chunks

**Comment by MaxNeedsSnacks** [comment]
FTB Chunks only handles (and cancels) server-side interactions. Sacks of Holding handle their initial interaction on the client side and send a "pick up entity" packet to the server, which among possible security issues (a "malicious" client could just arbitrarily send these packets to the server) also means that we can't stop it from doing that unless we introduce client-side checks, which means we would have to require Chunks to be on the client, as well
