### ISSUE TITLE
Blazes can spawn fire "blocks"

### ISSUE THREAD

**Issue by RGFTheCoder** [FTBTeam/FTB-Chunks#130]
Blazes are able to spawn fire "Blocks" in claimed chunks, which is different from the way it handles creeper explosions, where creepers cant damage claimed chunks. This could be used to grief wooden builds, by bringing a blaze from the nether.

**Comment by Shindur** [comment]
This also happens with skeletons that are on fire and shoot fire arrows. Had it happen to my base the other day in TNP Limitless 3 version 1.10.4
