### ISSUE TITLE
How does bypass_protection work?

### ISSUE THREAD

**Issue by OHQSaucey** [FTBTeam/FTB-Chunks#131]
How do I use this command? It seems like no matter what I try to type after it, it doesn't do anything. I am opped on my server and now I can't do things in other peoples claims anymore. How do I toggle this option on so it can work for ops?

**Comment by MaxNeedsSnacks** [comment]
You're not meant to type any arguments after it, if you just type `/ftbchunks admin bypass_protection` as an OP it toggles on/off for you and allows you to edit other people's claims

**Comment by OHQSaucey** [comment]
I had initially tried that and it did nothing. I tried it again and it worked. Why isn't there a prompt in console or chat that says you've enabled/disabled it? I wasn't sure if it was working at all because of that.
