### ISSUE TITLE
Players can step on pressure plates in claimed chunks.

### ISSUE THREAD

**Issue by Yucareux** [FTBTeam/FTB-Chunks#133]
Players can enter properties with claimed chunks if there is a pressure plate outside.

**Comment by Gunner76th** [comment]
This is something that cannot be avoided. Pressure plates are affected by weight interaction and not direct player interaction. This is why a Zombie or other mob that walks on your pressure plate will also trigger it. I suggest you use something more secure such as a button, something that actually requires player interaction.
