### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by celsiusqc** [FTBTeam/FTB-Chunks#135]
Hi,
Could you add a new option to FTBChunks so that you do not only have "Allies, Enemies, none". Could you add a new option that would allow players to only interact with chests / pressure plates but not break or place blocks? This could be useful for faction modpacks, which is what I am working on at the moment. Adding a config to toggle would also be great. You can dm me for more info or if you would like more explanations about my idea / suggestions
Thanks!

**Comment by Slowpoke101** [comment]
This is something that is possible, however just so you're aware, it is not
something that we can do right now. Our mod developers are currently snowed
under with work and we don't really have the time for at least a couple of
months to add additional features. I will however make sure it gets added
to the todo list.
