### ISSUE TITLE
bypass_protection node doesn't work if you're not opped

### ISSUE THREAD

**Issue by jinkhya** [FTBTeam/FTB-Chunks#137]
Hello, 
When you're not opped and have a rank with the permission node command.ftbchunks.admin.bypass_protection, you can run the /ftbchunks admin bypass_protection command (no red text telling you you don't have perms) yet you still can't bypass claims. I can confirm this command does works if you're opped. 

Forge 36.1.0
Ftb-chunks build 75
Ftb-ranks 1604 1.1.11

Thanks in advance

**Comment by MaxNeedsSnacks** [comment]
Thanks for bringing this to our attention! This is fixed in dev and will make its way into the next CurseForge release. Please keep in mind this one may take a little longer to release though as we're currently doing major overhauls with most of our mods!
