### ISSUE TITLE
How do i remove the FTB chunks Minimap

### ISSUE THREAD

**Issue by Ticskter** [FTBTeam/FTB-Chunks#138]
as the title states, how do i remove the mini map from FTB chunks, or utilities.. which ever one is adding it to the screen for All the Mods 6? I am a big fan of another mini map/large map mod and have it installed but i cant remove the "stock" map from the mod pack. and i cannot go into mods and config any of the mods from in game like ive been able to in the past.

**Comment by MichaelHillcox** [comment]
If I recall correctly, it's teams and to disable it, open your map using M and there should be a settings cog in the bottom left side of the screen, press that and you should see options for the map.

**Comment by LatvianModder** [comment]
in inventory, open FTB Chunks map icon, go in settings gear, set minimap to false

**Comment by Ticskter** [comment]
ah... i was making it harder than it needed to be.. thanks folks, much appreciated!!
