### ISSUE TITLE
map chunks is black this is my own modpack on fabric

### ISSUE THREAD

**Issue by alezhshede** [FTBTeam/FTB-Chunks#140]
![image](https://user-images.githubusercontent.com/82260461/115195505-20a14580-a0ef-11eb-97b9-d7e41698f073.png)

![image](https://user-images.githubusercontent.com/82260461/115195606-3e6eaa80-a0ef-11eb-89a7-b3ddccb6f6a7.png)

**Comment by OrionSincoat** [comment]
i'm also having the same bug on forge, sodium is causing this.

**Comment by ternsip** [comment]
Also having this, forced to use xaero

**Comment by MaxNeedsSnacks** [comment]
This is related to Sodium as Orion has already pointed out, and we'll have to look into whether we CAN even fix this ourselves
