### ISSUE TITLE
How to increase the Claimed Chunk Limit.

### ISSUE THREAD

**Issue by Furious1964** [FTBTeam/FTB-Chunks#142]
Please let me know as I've run out of chunks that can be clunkloaded. I'm trying to increase the limits for both the claimed and chunkloaded areas.

**Comment by Thevett** [comment]
I have also been searching for a way to do this. I have been watching some youtubers that use this mod and they have 36 available chunks to load while mine only has 9.

**Comment by MichaelHillcox** [comment]
It's in the config :+1:

**Comment by Furious1964** [comment]
No, it's not!

#Noise added to map to make it look less plastic
#Range: 0.0 ~ 0.5
noise = 0.05000000074505806
#Shadow intensity
#Range: 0.0 ~ 0.3
shadows = 0.10000000149011612
#Chunk grid overlay in large map
chunk_grid = false
#Reduces color palette to 256 colors
reduced_color_palette = false
#Color intensity
#Range: 0.0 ~ 1.0
saturation = 1.0
#Show claimed chunks on the map
claimed_chunks_on_map = true
#Show your own claimed chunks on the map
own_claimed_chunks_on_map = true
#Show waypoints in world
in_world_waypoints = true
#Enables creation of death waypoints
death_waypoints = true
#Different ways to render map
#Allowed Values: NONE, NIGHT, TOPOGRAPHY, BLOCKS, BIOME_TEMPERATURE, LIGHT_SOURCES
map_mode = "NONE"
#How many blocks should height checks skip in water. 0 means flat water, ignoring terrain
#Range: 0 ~ 128
water_height_factor = 8
#Enables minimap to show up in corner
#Allowed Values: DISABLED, BOTTOM_LEFT, LEFT, TOP_LEFT, TOP_RIGHT, RIGHT, BOTTOM_RIGHT
minimap = "DISABLED"
#Scale of minimap
#Range: 0.25 ~ 4.0
minimap_scale = 2.0
#Minimap will not rotate
minimap_locked_north = true
#Show waypoints on minimap
minimap_waypoints = true
#Show entities on minimap
minimap_entities = true
#Show entity heads on minimap
minimap_entity_heads = true
#Show player heads on minimap
minimap_player_heads = true
#Entities in minimap will be larger
minimap_large_entities = false
#Show XYZ under minimap
minimap_xyz = true
#Show biome under minimap
minimap_biome = true
#Blurs minimap
minimap_blur = true
#Adds NWSE compass inside minimap
minimap_compass = true
#Minimap visibility
#Range: 0 ~ 255
minimap_visibility = 255
#Show zone (claimed chunk or wilderness) under minimap
minimap_zone = true
#Enables debug info
debug_info = false

**Comment by MichaelHillcox** [comment]
Oh, then please provide your Game version and Mod version so I can look into the correct way to do this.

**Comment by Furious1964** [comment]
MC Version: 1.16.5
ATM 6 Version: 1.6.1
FTBChunks Version: 1605.2.3 Build 75

**Comment by MichaelHillcox** [comment]
Sorry, looks like it's a command now, not the config... My mistake... 
`/ftbchunks admin extra_claim_chunks <player> <add|set|get> <amount of chunks>`

**Comment by SakulXD** [comment]
I have the same problem with Seaopolis where can i edit that ?

**Comment by MichaelHillcox** [comment]
This command `/ftbchunks admin extra_claim_chunks <player> <add|set|get> <amount of chunks>` make sure to run as op

Going to close this issue now.
