### ISSUE TITLE
Re-add claim_as to command list

### ISSUE THREAD

**Issue by SilverKytten** [FTBTeam/FTB-Chunks#144]
I'm trying to set up a spawn and claim the chunks as such - In the wiki, it says to use /chunks claim_as, however I can't seem to do anything with that.

![image](https://user-images.githubusercontent.com/2188185/116007667-8ea9a900-a5d6-11eb-837c-2754e6c4a95a.png)

**Comment by MichaelHillcox** [comment]
Mod version, game version please.

**Comment by MaxNeedsSnacks** [comment]
Implemented in https://github.com/FTBTeam/FTB-Chunks/commit/97a359767d2ecde8ff89d6e8b1296f79ef715f83
