### ISSUE TITLE
Large amounts of claimed chunks prevent players from joining

### ISSUE THREAD

**Issue by copperwarrior** [FTBTeam/FTB-Chunks#148]
Currently running the latest release build of FTB Chunks (1605.2.3) on Forge 36.1.0 with other mods present.

We have a single modification to our FTB Chunks jar, replacing line 452 of src/main/java/com/feed_the_beast/mods/ftbchunks/FTBChunks.java from `chunk.allowExplosions()` to just `true`.

This modification was put in place to allow explosions in claimed chunks, as TNT explosions are a vital component to our server's progression, in order to break bedrock. It is my deductive opinion that this modification is not the cause of this issue, as it did not occur until the following events.

After setting maximum chunks to 3500 (a number I considered reasonable for the type of claims I was expecting my players to claim) and a player claiming that number of chunks, all players that attempt to connect are greeted with the following error:
`Internal Exception: io.netty.handler.codec.DecoderException: Badly compressed packet - size of 3257958 is larger than protocol maximum of 209715`

No related events are recorded to either client or serverside logs. Deduced it to be FTB Chunks by temporarily disabling the mod, which allowed connection.

Screenshot of error:
![image](https://user-images.githubusercontent.com/17477758/116551263-bd20d000-a8c5-11eb-8d87-339923bc05e3.png)

Screenshot of claim presumed to be causing the error:
![image](https://user-images.githubusercontent.com/17477758/116551303-cc078280-a8c5-11eb-912d-a0cc5328f5ef.png)

This screenshot was taken before the errors started. Judging by the accused player's actions to that point, my guess is that he tried to claim the entirety of the Mediterranean.

**Comment by MaxNeedsSnacks** [comment]
The initial chunk sync packet is probably too large because it doesn't anticipate such ridiculously huge claim numbers, so this is *probably* a bug on our end.

Until a patch for this is released (i.e. we implement proper packet splitting), which may take a while since we're currently busy with major updates to all of our mods,I suggest using something like [XL Packets](https://www.curseforge.com/minecraft/mc-mods/xl-packets) to increase your max packet size, as that should hopefully also prevent an error like that

**Comment by copperwarrior** [comment]
This workaround will work for me for now. Thank you for the response.

**Comment by copperwarrior** [comment]
As a bit more information for whomever picks this issue up, the amount of claimed chunks actually exceeded what I thought was the limit that I set. The user in question is one of my admins, and had given himself 60800 without notifying me. End file size was just under 1mb.
