### ISSUE TITLE
disable_protection doesn't do anything

### ISSUE THREAD

**Issue by LeoBeliik** [FTBTeam/FTB-Chunks#151]
changing the option "disable_protection" to false does not disable the chunk protection on claimed chunks, setting it to true also doesn't disable the protection.

tested with ftb-chunks-1605.2.3-build.75 and forge 36.1.13

**Comment by cdgamedev** [comment]
I know this is an old issue, but as a question, which config file did you edit? I just had the issue where I had to change both the `ftbchunks-server.toml` and the `ftbchunks.snbt` file in order to add additional chunk loading to players.

Might be the same issue for you?

**Comment by LeoBeliik** [comment]
there wasn't a `ftbchunks.snbt` when I opened this issue, yet I tested it now and the problem still persist.
