### ISSUE TITLE
Server Crash- Ftb Chunks Claiming

### ISSUE THREAD

**Issue by GabrielRaptorOneJohnstonGarbutt** [FTBTeam/FTB-Chunks#157]
[crash-2021-05-30_02.45.02-server.txt](https://github.com/FTBTeam/FTB-Chunks/files/6566584/crash-2021-05-30_02.45.02-server.txt)

**Comment by MichaelHillcox** [comment]
I can't see anything in your log blaming Chunks for that crash?
