### ISSUE TITLE
[feature] About adding mandatory loading block into block

### ISSUE THREAD

**Issue by GHOSTKING13** [FTBTeam/FTB-Chunks#159]
Please explain your issue in full and with as much detail as you can:
Hope to increase the possibility of adjusting the forced loading block, 25 grids are too few

**Comment by MaxNeedsSnacks** [comment]
You can add extra force-load chunks to players with a command (`/ftbchunks admin extra_force_load_chunks`) or use FTB Ranks or the config file (see your world's serverconfig folder) to increase that limit.
