### ISSUE TITLE
[bug] bypassProtection don't bypass `no_wilderness = true` protection.

### ISSUE THREAD

**Issue by Wojbie** [FTBTeam/FTB-Chunks#163]
When server is running in `no_wilderness = true` setting mode users are required to claim chunks to change world.
Expected `/ftbchunks admin bypass_protection` to allow operators to edit wilderness chunks.

**Mod & Pack version** ftb-chunks-1605.2.3-build.75.jar

**Forge / Fabric version, if applicable** forge-1.16.5-36.1.32.jar

**How to reproduce the issue**
*Please provide use with a step by step description*

Set server setting to `no_wilderness = true`
Run command `/ftbchunks admin bypass_protection` as operator.
Try to interact with wilderness.

**Anything else we should know?**
Operator can easly claim a chunk to edit it and then unclaim later so it is not a big issue but is a bit clunky to do it that way.

**Comment by LatvianModder** [comment]
Can you check if this works? https://maven.saps.dev/minecraft/dev/ftb/mods/ftb-chunks-forge/1605.3.1-build.32/ftb-chunks-forge-1605.3.1-build.32.jar

**Comment by Wojbie** [comment]
Server generated crash report.
Relevant excerpt:
```
Mod File: ftb-chunks-forge-1605.3.1-build.32.jar
Failure message: Mod ftbchunks requires ftblibrary 1 or above
Currently, ftblibrary is not installed
```
I have `ftb-gui-library-1605.2.1.41-forge` Do i need dev version of that too?

**Comment by MaxNeedsSnacks** [comment]
Yeah, you'll need to get the beta of FTB Library

**Comment by Wojbie** [comment]
Tried installing beta of mods that ftb chunks said it needs. Server runs fine but client crashes on r-click.
[crash-2021-07-21_14.28.27-client.txt](https://github.com/FTBTeam/FTB-Chunks/files/6855670/crash-2021-07-21_14.28.27-client.txt)

Unless you can point at specific versions i should use to test i am unsure how to proceed.

**Comment by LatvianModder** [comment]
that should be impossible... oh no

**Comment by LatvianModder** [comment]
Can you send latest.log after it crashes?

**Comment by Wojbie** [comment]
Sure. Here you go. Hope it helps.
[latest.log](https://github.com/FTBTeam/FTB-Chunks/files/6857235/latest.log)

**Comment by LatvianModder** [comment]
It did, I think its fixed now: https://maven.saps.dev/minecraft/dev/ftb/mods/ftb-chunks-forge/1605.3.1-build.33/ftb-chunks-forge-1605.3.1-build.33.jar

**Comment by Wojbie** [comment]
I can confirm it works as expected now. Thank you!
