### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by jrddunbr** [FTBTeam/FTB-Chunks#164]
Hi,

Your repository does not have a license indicated. The CurseForge website [here](https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge) indicates All Rights Reserved, while your organization's website specifies LGPL [here](https://feed-the-beast.com/mods) (you may need to change pages and search the page for FTB to find it).

Can you please add the license here and correct the license on CurseForge if they are incorrect?

Thanks!

**Comment by MichaelHillcox** [comment]
It's on my todo list but all FTB mods unless explicitly stated otherwise are only visible source and All Rights Reserved

**Comment by jrddunbr** [comment]
Noted, thanks.
