### ISSUE TITLE
[bug] Claiming as server doesn't claim as the serverteam but as the user issuing the command.

### ISSUE THREAD

**Issue by arseeeeN** [FTBTeam/FTB-Chunks#165]
**Mod & Pack version**
![image](https://user-images.githubusercontent.com/57875812/124586231-7d8edb00-de56-11eb-9a95-a7f32bdb52b9.png)
and Architectury Version 1.19.27-forge

**Forge / Fabric version, if applicable**
Forge Version 36.1.32

**Modpack (with version), if applicable**
https://www.curseforge.com/minecraft/modpacks/miss-myusagiis-custom-minecraft-modpack/files
Version 1.02.01

**How to reproduce the issue**
As the title says, using the /ftbchunks admin claim_server command with a valid server team as the team parameter just claims the chunks as the user that issued the command. (And even that is glitchy as it doesn't add the claimed chunks to the maximum chunks claimed until you claim another chunk by hand.)

It probably has to do with the private claimServer() function in FTBChunksCommands.java not using the "team" parameter but rather the "source" which just contains the user that issued the command.

**Comment by MaxNeedsSnacks** [comment]
I'm pretty sure that command was just never adjusted for the new teams system, which makes it so you can have multiple different server teams. I've forwarded it to Lat since I unfortunately can't work much on mods this week, but a fix for this should hopefully be out soon
