### ISSUE TITLE
[bug] Mincraft crashes during start

### ISSUE THREAD

**Issue by KorocDM** [FTBTeam/FTB-Chunks#166]
To help us help you, please provide as much information as you can, this helps us with debugging and reproducing the issue.

**Forge / Fabric version, if applicable**
ftb-chunks-fabric-1605.3.1-build.20

**If the issue is a crash; An external link to the crash report**
[crash-2021-07-06_14.41.04-client.txt](https://github.com/FTBTeam/FTB-Chunks/files/6770083/crash-2021-07-06_14.41.04-client.txt)

**How to reproduce the issue**
*Please provide use with a step by step description*
I just try to launch the game with the fabric1.16.5 loader

**A screenshot, if applicable**
The game crashed whilst initializing the game.
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'ftbchunks'!
Exit-Code: -1

**Anything else we should know?**
I only have the dependency mods in the mod folder.

**Comment by MaxNeedsSnacks** [comment]
Your versions of FTBTeams (and FTBRanks) are outdated, we repackaged to dev.ftb.mods

Please update those two and try again

**Comment by KorocDM** [comment]
Thanks for the quick response!
I have downloaded the latest versions of FTBTeams and FTBRanks from
curseforge and it still gives me the same error code. Is there a newer
version that I can get somewhere else?
what do you mean with "we repackaged to dev.ftb.mods"
