### ISSUE TITLE
[bug] FTB-chunks map will not load an 11x11 chunk square centered on spawn

### ISSUE THREAD

**Issue by NillerMedDild** [FTBTeam/FTB-Chunks#167]
Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/2738

Upon spawn in on a new world, FTB-chunks map will not load an 11x11 chunk square centered around the chunk the player spawns in. The issue persists upon the deletion of a world and recreation of a new world (on a server).

**Mod & Pack version**
- ftb-chunks-forge-1605.3.1-build.24

**Forge / Fabric version, if applicable**
- Forge

**Modpack (with version), if applicable**
- Enigmatica6-0.5.6

**If the issue is a crash; An external link to the crash report**

**How to reproduce the issue**
- Create a new world
- Check the map

**A screenshot, if applicable**
![2021-07-14_22 45 09](https://user-images.githubusercontent.com/21284670/125721748-f9a7d9d2-af34-4d2e-839b-ac5be7dbd834.png)
![2021-07-14_23 05 57](https://user-images.githubusercontent.com/21284670/125721792-06cbcd77-2e17-403f-91d2-284f1f8f3389.png)

**Anything else we should know?**
The issue persists in new worlds

**Comment by MaxNeedsSnacks** [comment]
Should be fixed in the latest release, thanks Lat
 ^^

**Comment by NillerMedDild** [comment]
Awesome!
