### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by Furious1964** [FTBTeam/FTB-Chunks#169]
**Mod & Pack version** FTB-Chunks 1605.3.1

**Forge / Fabric version, if applicable** Forge 36.1.32

**Modpack (with version), if applicable** ATM6 1.7.1

**How to reproduce the issue**
Use command to give more chunks...doesn't work.
*Please provide use with a step by step description*
/ftbchunks admin extra_force_load_chunks Player Name set 500 does not work!

Please tell me if this has changed as it no longer works.

**Comment by MaxNeedsSnacks** [comment]
Fixed in https://github.com/FTBTeam/FTB-Chunks/commit/6317a3aab5341ffb6269a5568cd611995cb4b1a0
