### ISSUE TITLE
[bug] Chunk claim limit not working when joining a team

### ISSUE THREAD

**Issue by yuesha-yc** [FTBTeam/FTB-Chunks#172]
To help us help you, please provide as much information as you can, this helps us with debugging and reproducting the issue.

**Mod & Pack version**
ftb-chunks-forge-1605.3.1-build.31

**Forge / Fabric version, if applicable**
Forge

**Modpack (with version), if applicable**

**If the issue is a crash; An external link to the crash report**

**How to reproduce the issue**
*Please provide use with a step by step description*
Create a team, then claim chunks. 

**A screenshot, if applicable**

**Anything else we should know?**

**Comment by MaxNeedsSnacks** [comment]
I can't seem to reproduce any issues, what exactly is wrong here?
