### ISSUE TITLE
[bug] Fluid placement in a claim area 

### ISSUE THREAD

**Issue by Gogo08190** [FTBTeam/FTB-Chunks#173]
To help us help you, please provide as much information as you can, this helps us with debugging and reproducting the issue.

**Mod & Pack versdion**

ftb-chunks-forge-1605.3.1-build.34

**Forge / Fabric version, if applicable**

Forge

**Modpack (with version), if applicable**

Chroma Technology 2 v-1.0.3

**If the issue is a crash; An external link to the crash report**

**How to reproduce the issue**
*Please provide use with a step by step description*

We cannot place water or retrieve water in a claim area. Same for lava or any fluid

**A screenshot, if applicable**

**Anything else we should know?**

**Comment by Ki-Tan2934** [comment]
Works in version ftb-chunks-forge-1605.3.1-build.31

**Comment by hvdklauw** [comment]
Same in CreateTogether modpack version 1.1.4

**Comment by Nyinxie** [comment]
My players in my server are also having this issue

**Comment by LatvianModder** [comment]
To be clear, is it in your own or someone *else's* claim? Because you arent supposed to be able to place/pick up fluids in someone else claims, only your own and wilderness

**Comment by Gogo08190** [comment]
It's in my claim

**Comment by LatvianModder** [comment]
I think I found the issue, should be fixed in next update

**Comment by Gogo08190** [comment]
Thanks a lot !

**Comment by LatvianModder** [comment]
https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge/files/3401679
