### ISSUE TITLE
[bug] Allied/trusted Modular Routers do not work in claimed chunks

### ISSUE THREAD

**Issue by NillerMedDild** [FTBTeam/FTB-Chunks#177]
**Mod & Pack version**
ftb-chunks-forge-1605.3.1-build.24

**Forge / Fabric version, if applicable**
Forge

**Modpack (with version), if applicable**
Enigmatica 6 0.5.6

**How to reproduce the issue**
*Please provide use with a step by step description*

When a modular router with a placer module is placer in a claimed chunk it will not place. The player has verified that fake players are allowed in the FTB teams settings. The player unclaimed the chunk and the router placed blocks correctly. When the chunk was claimed again the router stopped placing blocks.

Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/2838

**Comment by MaxNeedsSnacks** [comment]
Correction: Since this was in version **0.5.6** of Enigmatica 6, you were using `ftb-chunks-forge-1605.3.1-build.24.jar` ^^

Please try reproducing this on build 36, as we've overhauled the protection system since then

**Comment by NillerMedDild** [comment]
Ah so it was, my bad ^^'

**Comment by NillerMedDild** [comment]
Seems fixed in build.24 :D
