### ISSUE TITLE
Friendlist Disabled

### ISSUE THREAD

**Issue by AzureZeroFrog** [FTBTeam/FTB-Chunks#178]
Cannot add friends to chunks. 

Pressing M and the little "recycle symbol" (friend list symbol says) "Current Disabled due to bug"

**Comment by AzureZeroFrog** [comment]
![image](https://user-images.githubusercontent.com/87950370/127860719-5af19481-20af-4f51-ac97-25ffa3e36e32.png)

**Comment by coco009876** [comment]
Same to me, nothing yet?
