### ISSUE TITLE
[bug] Supplementaries signs can be edited in other people's claims

### ISSUE THREAD

**Issue by NillerMedDild** [FTBTeam/FTB-Chunks#181]
Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/2916

**Mod & Pack version**
ftb-chunks-forge-1605.3.1-build.36

**Forge / Fabric version, if applicable**
Forge

**Modpack (with version), if applicable**
Enigmatica 6 v0.5.8

**How to reproduce the issue**
*Please provide use with a step by step description*
- Claim a chunk
- Place a Supplementaries sign in it
- Have someone untrusted edit it

**Comment by MaxNeedsSnacks** [comment]
I'm not exactly sure whether we can do anything about this, as from what I remember, the sign editing is done on the client side, and any chunks we have to manage interactions are handled by the server.

**Comment by NillerMedDild** [comment]
The edit must resolve as a server event though, for the text to actually update?
