### ISSUE TITLE
[bug] Crash when clicking on Settings gear

### ISSUE THREAD

**Issue by hron84** [FTBTeam/FTB-Chunks#184]
To help us help you, please provide as much information as you can, this helps us with debugging and reproducting the issue.

**Mod & Pack version**
1605.3.1-build.41

**Forge / Fabric version, if applicable**

Minecraft Version: 1.16.5
Forge Version: 36.2.2

**If the issue is a crash; An external link to the crash report**

https://gist.github.com/hron84/cc34c389b7330ab3d791edda90317979

**How to reproduce the issue**
Open FTB Chunks GUI and click on the Settings gear.

**Comment by shouta65** [comment]
Same here. It seems BaseScreen#getWrapper is removed from FTB-Library at 1605.3.2 (build 64) https://github.com/FTBTeam/FTB-Library/commit/85ebdb17e6cb5bfc1642c8748942e82410eee378
BaseScreen#getWrapper is used in [LargeMapScreen.java](https://github.com/FTBTeam/FTB-Chunks/blob/main/common/src/main/java/dev/ftb/mods/ftbchunks/client/LargeMapScreen.java) line 143.

**Comment by MaxNeedsSnacks** [comment]
> Same here. It seems BaseScreen#getWrapper is removed from FTB-Library at 1605.3.2 (build 64) [FTBTeam/FTB-Library@85ebdb1](https://github.com/FTBTeam/FTB-Library/commit/85ebdb17e6cb5bfc1642c8748942e82410eee378)
> BaseScreen#getWrapper is used in [LargeMapScreen.java](https://github.com/FTBTeam/FTB-Chunks/blob/main/common/src/main/java/dev/ftb/mods/ftbchunks/client/LargeMapScreen.java) line 143.

Yep, Lat seems to have pushed a breaking change in a minor release and I shouldn’t have merged that, we’ll probably have to update all of our mods that rely on Library‘s GUIs

**Comment by MaxNeedsSnacks** [comment]
Fixed in the most recent release ^^
