### ISSUE TITLE
[feature] Disable Chorus Fruit Teleportation Inside Protected Chunks

### ISSUE THREAD

**Issue by ExDomino** [FTBTeam/FTB-Chunks#185]
Hello, is there a way to disable the ability to teleport inside protected slots with a Chorus Fruit please ?
Ender pearls is not really a problem since it cannot allow pass throught walls.

Thank you in advance.

**Comment by MaxNeedsSnacks** [comment]
There isn't and also probably won't be a way in FTB Chunks, but you could use something like KubeJS (if that has a teleport event, not sure) to cancel people teleporting in there with chorus fruits or ender pearls.
