### ISSUE TITLE
Chunk config File

### ISSUE THREAD

**Issue by Elmani335** [FTBTeam/FTB-Chunks#23]
**Hello !** 
you have changed the Ranks **.json** to **.txt**
so now **how** can we change the **max claimed chunks** and **loaded chunks** _for players_ ?

**Comment by SevenChords** [comment]
i need to know this as well, having issues with claiming all the base chunks on bigger teams on our server

**Comment by MelanX** [comment]
In the Server config? If you’re on SP, look in your world folder
Idk if this is right

**Comment by LatvianModder** [comment]
https://faq.ftb.world/books/ftb-utilities/page/frequently-asked-questions
