### ISSUE TITLE
Server Crash ftb-chunks-1.1.0.12 

### ISSUE THREAD

**Issue by ClaudiusMinimus** [FTBTeam/FTB-Chunks#27]
This morning I noticed my test server was down. I checked the crash reports and found the following:

https://pastebin.com/Pcvf0sFL

- Minecraft Version: 1.15.2
- Operating System: Linux (amd64) version 4.15.0-99-generic
- Java Version: 1.8.0_251, Oracle Corporation
- Forge: 31.2.0
- ftb-chunks-1.1.0.12

Just talked to the player and he said, "I went into my newly created Ratlantis portal, and crashed when I entered the dim"

**Comment by sarahriously** [comment]
Had the exact same crash, FTB Omnia running ftb-chunks-1.1.0.12.
According to a player, happened shortly after loading Ratlantis for the first time, but not immediately when it happened.

**Comment by phit** [comment]
same issue with `ftb-chunks-1.1.0.14` in All The Mods 5
