### ISSUE TITLE
FTB Chunks minimap not showing claimed chunks

### ISSUE THREAD

**Issue by RealDimi** [FTBTeam/FTB-Chunks#29]
Would it be possible to show the claims on the minimap?

**Comment by twipsta** [comment]
I also have a similar problem. Unsure if the same cause or not.
I am running the FTB Omnia pack and for me the Chunks map seems to work fine in all dimensions except for the void dimension where it will show no map or claimed chunks at all. This only started happening after updating to FTB Omnia 1.5.0

Clicking on the map in this state does still seem to (un)claim/load chunks but there is no visual represntation.
Claimed areas in the dimension are still protected as I found out when trying to get a RFTools Builder to work - I hadn't allied the fake player so it couldn't do anything.

I am not sure what info you would need to help track down the problem, but I am happy to try and provide what you need.
I have included some screenshots to try and show the issue

As you can see, in the Overworld everything works as expected:
![2020-07-21_10 58 10](https://user-images.githubusercontent.com/8107510/88000564-48a05000-cb41-11ea-86cb-d654c41a2c1f.png)

But in the void dimension it is blank, and the majority of chunks in this area should show as claimed:
![2020-07-21_10 58 38](https://user-images.githubusercontent.com/8107510/88000568-4a6a1380-cb41-11ea-9cad-84d51f4fc2a5.png)

I have tried clearing out the map images both client and server side hoping they would regenerate, and they technically do but they don't show in game. But if I check the map directories again there are new images with feint overviews of players bases.
I also tried to force the server to send all generated Chunks maps using "ftbchunks admin export_whole_map [player]" in console.

Other info that might help:
FTB Omnia 1.5.0 (recently upgraded)
ftb-chunks-1.1.0.12
Java 8 Update 261 (client side, recently upgraded)
OpenJDK JRE build 1.8.0_252 (server side)

If this is different to OP's issue let me know and I will open a seperate ticket.

**Comment by MaxNeedsSnacks** [comment]
Should no longer be an issue in 1.16 releases, feel free to reopen if it is.
