### ISSUE TITLE
[1.15.2] Mod Interaction JEI

### ISSUE THREAD

**Issue by TheUntamed** [FTBTeam/FTB-Chunks#30]
The map and book button are overlaying the JEI bookmark list. Could you move the buttons to the top-center of the screen or add a button to move them around like it is possible with the minimap?

![Screenshot_1](https://user-images.githubusercontent.com/48363903/88692124-01482f80-d0fe-11ea-940d-eff5c6591276.jpg)

**Comment by MaxNeedsSnacks** [comment]
Should no longer be an issue in 1.16 releases, feel free to reopen if it is.
