### ISSUE TITLE
[1.16.1] Client crash when on MP and tries to open map.

### ISSUE THREAD

**Issue by WhitePhant0m** [FTBTeam/FTB-Chunks#31]
[Crash report](https://pastebin.com/qmmxTvUL)
Server stays up but the connected client crashes when opening map, either by clicking the button or pressing key bind.

**Comment by WhitePhant0m** [comment]
ftb-chunks-1.1.1.19 seems to have fixed it.

**Comment by ovingiv** [comment]
Unfortunately my friends and I are crashing when trying to open the map both on the server and in single player.
Crash Report: https://pastebin.com/U9UJPrcY
