### ISSUE TITLE
Deaths via server watchdog, seem to be mostly a result of server rendering function in ftb chunks?

### ISSUE THREAD

**Issue by Darinth** [FTBTeam/FTB-Chunks#32]
https://pastebin.com/0fmdrRez

I'm not certain ftb chunks is the responsible mod, but having a lot of crashes where the only mod that shows up in the crash log is ftbchunks. Example log is provided above. Have a dozen logs from the past 2 days where the server crashes, most of which are a similar log. Most of them are during ReloadChunkTask. I've tried disabling the watch dog, when I do so the server simply hangs until I kill it manually.

Mod Version: ftb-chunks-1.1.0.16
Forge version: 31.2.33

Running FTB Omnia

**Comment by Darinth** [comment]
I'm happy to try updating to the most recent (1.1.1.17 as of this post) version available on forge. Do you know if doing so on the server will require all of my players to also do said update?

**Comment by MaxNeedsSnacks** [comment]
This seems to have been caused by Performant originally, and it should no longer be an issue in 1.16 releases, hopefully
