### ISSUE TITLE
Chunk loading without claiming

### ISSUE THREAD

**Issue by Darinth** [FTBTeam/FTB-Chunks#33]
Any chance of having the option to load a chunk without claiming it? Typical pack setups prevent fake player actions from performing any actions in claimed chunks and those claimed chunks are often the same ones we actually want to chunk load to keep distant machines running. Thus the ability to load without claiming a chunk (or maybe disabling the fake-player protection on that specific chunk?) would be necessary for these kinds of machines to run.

**Comment by MaxNeedsSnacks** [comment]
We won't be supporting that because it would completely break the current chunk infrastructure, but we will be adding a command to claim as a server team, for which you will then be able to allow interactions by default
