### ISSUE TITLE
Crashing when trying to open the map [1.16.1 ATM6]

### ISSUE THREAD

**Issue by ovingiv** [FTBTeam/FTB-Chunks#35]
My friends and I are all crashing when we try to open the map either by clicking on it or pushing the key binding to it. Not sure what changed as we used it when we first started playing to claim chunks/chunk load and I do see that the server is loading those chunks.

Crash Report: https://pastebin.com/U9UJPrcY

**Comment by ovingiv** [comment]
I found the issue. Somehow, I had ftb-gui-library-1.0.0.18.jar and ftb-gui-library-1.0.0.15.jar in my mods folder which was causing my issue. Removing ftb-gui-library-1.0.0.18.jar solved it and it no longer crashes my game.

**Comment by rlcold** [comment]
hello man, do you still have ftb-gui-library-1.0.0.15.jar? If so could attach and send me the love of Herobrine?

**Comment by xPatrikPvP** [comment]
https://jenkins.latmod.com/job/FTB-GUI-Library/15/
