### ISSUE TITLE
Mixin related crash on joining world

### ISSUE THREAD

**Issue by Charismara** [FTBTeam/FTB-Chunks#38]
FTB-Chunks: 1.1.1.35
FTB-GUI_Lib: 1.0.0.18
Forge: 34.1.5
Minecraft: 1.16.3

[Crash Report](https://pastebin.com/THuZmyDM)

The Game just crashed when i try to join a singleplayer world.

**Comment by MaxNeedsSnacks** [comment]
Should no longer be an issue in the newer 
1.16.5 releases, feel free to reopen if it is.
