### ISSUE TITLE
worlds not able to be deleted

### ISSUE THREAD

**Issue by redo6565** [FTBTeam/FTB-Chunks#39]
tried to delete so test worlds and the world are not being deleted with the mod installed in 1.16.3

**Comment by Rensik** [comment]
Still happening in 1.16.4. Once a player loads into a world, that world is no longer able to be deleted while the game is running. The game process must first be exited and then the folder for the world can be removed. The FTB Chunks folder inside the save becomes Read Only and permissions to remove it become inactive/toggled off while the game is running. I feel like this is an oversight.

**Comment by MaxNeedsSnacks** [comment]
This has been fixed in newer releases according to Lat
