### ISSUE TITLE
[1.16.3] Crash to desktop if the server stops while looking at the map

### ISSUE THREAD

**Issue by AtomicBlom** [FTBTeam/FTB-Chunks#41]
G'day Crew.

Had this crash on Forgecraft:

Steps to reproduce:
1. Join a multiplayer server.
2. Open the claim chunk map
3. Shut down the server

Expected result:
I am dropped to the main menu.

Actual result:
Game hard crashes.

Log:
https://gist.github.com/AtomicBlom/d1990d39cc3dd5f555a9f0a789b70322

Minecraft version: 1.16.3
Mod version: 1.1.2.36

**Comment by MaxNeedsSnacks** [comment]
Should no longer be an issue on 1.16.5?
