### ISSUE TITLE
[1.16.3] Config Questions

### ISSUE THREAD

**Issue by YOYOK9** [FTBTeam/FTB-Chunks#43]
Hello, this is mainly just a question about how the config is configured for adding more dims to the clam blacklist. Currently there is only: claim_dimension_blacklist = ["minecraft:the_end"] , 

Im not 100% formillar with the new json style configs just yet. So I am wondering how to add the nether to this as well. I tried  ["minecraft:the_end,the_nether"] and it didnt crash however when I went and added quark it crashed due to not finding the world minecraft:the_end,the_nether. 

What is the correct syntax for this? An example would be nice in the wiki (currently empty)

**Comment by MaxNeedsSnacks** [comment]
You'd need to add it in the form of separate strings, so
`["minecraft:the_end", "minecraft:the_nether"]`

where each 
one string would be one dimension id
