### ISSUE TITLE
crash on launch [1.16.3] [Description: Rendering overlay  java.util.ConcurrentModificationException: null]

### ISSUE THREAD

**Issue by SDUBZ** [FTBTeam/FTB-Chunks#45]
forge: 1.16.3-34.1.34
ftb chunks: ftb-chunks-1603.1.2.40

notes:
could related to changes in forge

logs:
[latest.log](https://github.com/FTBTeam/FTB-Chunks/files/5458223/latest.log)
crash report:
[crash-2020-10-29_23.08.13-client.txt](https://github.com/FTBTeam/FTB-Chunks/files/5458226/crash-2020-10-29_23.08.13-client.txt)

**Comment by MaxNeedsSnacks** [comment]
Should no longer be an issue the newest releases, feel free to reopen if it is.
