### ISSUE TITLE
FTB-Chunks 1.12.2 Request

### ISSUE THREAD

**Issue by Pel00** [FTBTeam/FTB-Chunks#46]
Hi
I just found this mod. If It's possible, can make you can make this mod for MC 1.12.2 Forge version? I'm making a huge modpack and this mod will be very useful.

**Comment by FlambeSk** [comment]
For 12.2.2 is [FTB Utilities](https://www.curseforge.com/minecraft/mc-mods/ftb-utilities)

**Comment by MaxNeedsSnacks** [comment]
As FlambeSk said, 1.12.2 already has FTB Utilities which contains all of the Chunks functionality as well
