### ISSUE TITLE
[1.16.3] Allied shared maps are... interesting

### ISSUE THREAD

**Issue by drewbit** [FTBTeam/FTB-Chunks#48]
FTB Chunks Version: 1603.2.0.42
Forge Version: 34.1.42

Currently, when you receive a shared map from an allied player it looks like this. 
![image](https://user-images.githubusercontent.com/17441782/98191521-99606c80-1ed6-11eb-8ea2-71f9c7d7539c.png)

Fairly sure that's a bug.

**Comment by jaynesb** [comment]
I'm seeing this as well. And there doesn't seem to be any way to force the bugged chunks to refresh and look normal.

**Comment by KonradStuewe** [comment]
Modpack: All The Mods 6 1.3.2c
forge-35.1.4
ftb-chunks-1603.2.0.43

Same problem.

![Image of Map](https://cdn.discordapp.com/attachments/781221211924594740/781921665704787998/unknown.png)
