### ISSUE TITLE
[1.16.3] Crops not ticking in loaded chunks

### ISSUE THREAD

**Issue by JeffersonDoan** [FTBTeam/FTB-Chunks#49]
FTB Chunks Version: 1603.2.0.42
Forge Version: 34.1.42

Crops are not ticking in the latest version of FTB Chunks.

In [this recent commit](https://github.com/FTBTeam/FTB-Chunks/commit/d17ef0bf43e7c488378a037f5b280f7356db0f5b) in [FTBChunksConfig.java](https://github.com/FTBTeam/FTB-Chunks/blob/master/src/main/java/com/feed_the_beast/mods/ftbchunks/FTBChunksConfig.java#L136) I saw this method always returning false:

```
public static boolean patchChunkLoading(ServerWorld world, ChunkPos pos)
{
	if (patchChunkLoading)
	{
		return false;
	}

	return false;
}
```

Is there still more to this not yet implemented or should it just return true according to what is in the config?

**Comment by FlambeSk** [comment]
Does this work even player is offline and there are no othe players on server?

**Comment by JeffersonDoan** [comment]
Just tested on a local server on 1.16.4 with Forge 35.1.2 and this does work while players are offline.

**Comment by FlambeSk** [comment]
Can you send me edited and builded jar file for 1.16.4? I am trying build project but unsuccessfully.

Thank you so much !

**Comment by FlambeSk** [comment]
Working for me too, just tested. Thank you so much !
