### ISSUE TITLE
waystones and FTB chunks causing crashes

### ISSUE THREAD

**Issue by TheTaterLord** [FTBTeam/FTB-Chunks#51]
Activating someone's waystone in their chunks when you aren't allied causing the server to either crash or timeout couldn't find a config option for it in either mod

**Comment by AlieDupuis** [comment]
To add to this..
After activation, non-allied players can't teleport to your location using the Waystone. Would be nice to set exceptions for actions players can and can't do within claimed chunks

**Comment by MaxNeedsSnacks** [comment]
This should be fixed in newer versions, feel free to reopen if it still occurs
