### ISSUE TITLE
Minimap displaying white?

### ISSUE THREAD

**Issue by MdBourg98** [FTBTeam/FTB-Chunks#52]
![image](https://user-images.githubusercontent.com/57682576/99246540-75a0fe80-27d3-11eb-80f2-859bc2c0006c.png)

**Comment by Xertzakzul** [comment]
Same problem here

**Comment by dr3ams** [comment]
Same

**Comment by rodrigoaddor** [comment]
I also got that problem, in a custom modpack where none of my friends got such problem, with the same configs. Maybe it's related to some graphics setting?

**Comment by Xertzakzul** [comment]
Well last weekend, I updated my nVidia drivers and after that, minimap start working correctly. No white texture anymore.

**Comment by rodrigoaddor** [comment]
I didn't update my drivers, but today I updated my Windows (Insider build, Dev channel) and... it's fixed. Really weird issue.

**Comment by miha-meglic** [comment]
Same here... fixed with a graphics driver update.

**Comment by MaxNeedsSnacks** [comment]
Should be fixed in newer releases / with newer graphics drivers
