### ISSUE TITLE
1.15.2 Chunk loading doesn't work

### ISSUE THREAD

**Issue by Hiranus** [FTBTeam/FTB-Chunks#53]
As stated above, chunk loading doesn't seem to work properly. I chunkloaded simple carrot farm that has nothing but vanilla stuff and nothing has grown. Tried it again with villagers and they were not breeding properly.

**Comment by FlambeSk** [comment]
Same here in version 1.16.4.

**Comment by slebreton79** [comment]
Ditto in 1.16.4 but custom modpack....

**Comment by FlambeSk** [comment]
Working solution [here](https://github.com/FTBTeam/FTB-Chunks/pull/54), tested by myself.

**Comment by MaxNeedsSnacks** [comment]
Should also be fixed in newer releases.
