### ISSUE TITLE
[1603.2.0.43@1.16.4] Chunks not populating in map

### ISSUE THREAD

**Issue by SkyeRise** [FTBTeam/FTB-Chunks#56]
Very frequently the map chunks of the map and minimap are partially unpopulated. In these areas no F3+A or even saving to main menu and loading will make these parts of the map functional. In these broken areas, chunk claiming is also either broken or visually hidden. I am using experimental Biomes'O'Plenty for which I am getting the "There be dragons" warning in case this may be relevant. In any case, you need to add some extra integrity checks and give the mod the ability to attempt creating map chunks again. Also, maybe try to give chunks more time so they can go through all the generation process. With Biomes'O'Plenty (at least this was the case in the past) there are additional later generation steps that might be clashing with FTB Chunks rushing in too quickly.

**Comment by desagas** [comment]
I am having the exact same issue, in 1604.2.2.62, playing in ATM6. Often times, when exploring large areas, the map will stop. It is almost as if the map data is not being cleared, remaining in memory, and the buffer becomes full, not allowing any additional data to be sent or received.

**Comment by desagas** [comment]
This is a log of the failed FTBChunk Update.

[FTBChunksLog.txt](https://github.com/FTBTeam/FTB-Chunks/files/5968409/FTBChunksLog.txt)

**Comment by MaxNeedsSnacks** [comment]
Can you test this again with the newest release?
