### ISSUE TITLE
[1.16.4 Bug] Fake player displayed in Allies GUI

### ISSUE THREAD

**Issue by ScottCTD** [FTBTeam/FTB-Chunks#59]
Just like what the image says:
![image](https://user-images.githubusercontent.com/35100768/100533947-2338f680-3245-11eb-91ff-54e80c4834ba.png)

I suggest not to display those fake players in this GUI.

Thanks and sorry for troubling you!

**Comment by ScottCTD** [comment]
Also, when the cyclic forester is in my chunks, it could not work.
However, if I delete the chunk and then the forester will work.

Therefore, I think it is more like an issue related to the fake players.

**Comment by MaxNeedsSnacks** [comment]
This is intentional, and Cyclic creating a fake player for each harvester is a bug on Cyclic's end
