### ISSUE TITLE
[Suggestion] Cave/Underground Mode

### ISSUE THREAD

**Issue by Desempregago** [FTBTeam/FTB-Chunks#62]
*the title explains itself.*

**Comment by MokahTGS** [comment]
Yeah...this is needed for it to be useful.

**Comment by willrun4fun** [comment]
I also want this.

**Comment by Ezoteric** [comment]
I 3rd this!! :)

**Comment by SWJ0k3r** [comment]
It seems like this request is being ignored. Is there an expectation that the devs are hoping someone will make a pull request to add this?

**Comment by MaxNeedsSnacks** [comment]
> It seems like this request is being ignored. Is there an expectation that the devs are hoping someone will make a pull request to add this?

PRs are always appreciated, ~~but frankly, Latvian just doesn't check GitHub and that's why I'm here now~~

**Comment by carneeki** [comment]
I too would like to see this.

Willing to help write + test. I'm good with Java, but haven't done any MC mods before so will need some guidance.
