### ISSUE TITLE
Claim team color missing on maps [1.16.3]

### ISSUE THREAD

**Issue by aharrisw** [FTBTeam/FTB-Chunks#64]
I updated from ftb-chunks-1603.2.0.47 to the latest ftb-chunks-1604.2.1.49 release to fix the issue of random ticks not working in loaded chunks (crops, etc.) and now the maps don't have the claim team colors. They were there working just fine in .47. Luckily there is still a white outline to kind of see where the claims are.

[Link to Example](https://cdn.discordapp.com/attachments/274082706801950721/785856211047284736/eac0eceed76a7254751fd648afb6f7a6.png)

**Comment by MaxNeedsSnacks** [comment]
Should be fixed in newer releases, if you still encounter it, feel free to reopen!
