### ISSUE TITLE
MapDimension.getCurrent crash

### ISSUE THREAD

**Issue by CHollman822** [FTBTeam/FTB-Chunks#67]
When pressing m to view the map I'm kicked out of the game, here is the crash log:

[crash-2020-12-10_17.23.09-client.txt](https://github.com/FTBTeam/FTB-Chunks/files/5675985/crash-2020-12-10_17.23.09-client.txt)

**Comment by CHollman822** [comment]
Solved, my fault, sorry.

**Comment by meschbach** [comment]
@CHollman822 I hit a similar issue on 1.16.5.  Any pointers on what I can try to work around this?
