### ISSUE TITLE
[Question] Where is the map data stored

### ISSUE THREAD

**Issue by judicius** [FTBTeam/FTB-Chunks#68]
Where is the player map data stored? I just want to delete the stored map data for a specific UUID/Player.

**Comment by SleepyCatGuy** [comment]
I also wish to know this as some of my chunks became darker after getting shared with from a Allie and would like to completely reset my map.

**Comment by SleepyCatGuy** [comment]
So after 2 min of looking I found it in '<modpack_instance>/local/ftbchunks/data/<UUID>/'
