### ISSUE TITLE
Block "Drawbridge" from "Tinkers' Mechworks" is not working in claimed chunks.

### ISSUE THREAD

**Issue by smallerYeet** [FTBTeam/FTB-Chunks#72]
The Mod "[Tinkers' Mechworks"](https://www.curseforge.com/minecraft/mc-mods/tinkers-mechworks) is not working in claimed chunks. 
After removing the claim it's operating again.

Mc: 1.16.3
Forge: 34.1.42
Mod version: 1604.2.1.49

**Comment by ianlavr** [comment]
Maybe this because drawbridge uses a fake player?

**Comment by Splinti** [comment]
Hi!
You need to make allies with the "MechworksWorker", this fixes the issue
