### ISSUE TITLE
[1.16.4] Config to disable offline chunkloading

### ISSUE THREAD

**Issue by NillerMedDild** [FTBTeam/FTB-Chunks#73]
Hi there!

It would be very useful to have a setting to disallow chunkloading for players that are not online on the server. The Enigmatica 6 server is having issues with laggy bases, despite very few people being online. I believe disallowing offline chunkloading would remedy most of that.

I hope you'll consider it :)

**Comment by Ridanisaurus** [comment]
I can't stress how useful this config would be for server management where optimization of farms and tile entity ticking is not a common practice for your average player, and then adding Chunkloading on top of that makes it a nightmare for TPS.

As Niller said, I hope you'll consider adding this config.

**Comment by Bubble0seven** [comment]
I concur this feature i feel is vital for any server management.

**Comment by 648643579** [comment]
This feature is really indispensable for servers, please add feature and thank you for your work.

**Comment by jinkhya** [comment]
FTB Utilities used to have that feature with the permission node, I'm really looking forward to seeing this return in 1.16! :)
On a server with around 30 players logging (from different timezones) makes it quite difficult to handle if everybody's base is chunkloading non-stop.
