### ISSUE TITLE
Flame Enchant Bow OR Arrow + Lava/Fire = Burned down house

### ISSUE THREAD

**Issue by kingadams** [FTBTeam/FTB-Chunks#76]
Greetings and Merry Christmas to all,

I don't know if this is an intentional mechanic of FTB-Chunks, or an oversight.  I have recently discovered however that anyone with an bow with the enchantment flame can burn down your base you made within your claim.  I had this happen with a skeleton, and had some friends test it out.  Another issue is when a friend outside of your claim places down fire or lava and fires arrows into your claim.  That will set it on fire as well.  

The easy temp fix for us now is to disable firespread obviously.  
 
**Minecraft Version:** 1.16.4
**Forge Version:** forge-35.1.13
**Plugin Version:** ftb-chunks-1604.2.1.51  (We will update to the latest soon to see if it continues, but we did not see any changelog indicating otherwise).

**Comment by MaxNeedsSnacks** [comment]
I don't think Vanilla flames set blocks on fire by default, are you sure this is reproducable just with FTB Chunks?
