### ISSUE TITLE
Productive Bees crashing when trying to interact in claimed chunks

### ISSUE THREAD

**Issue by wheelsfire** [FTBTeam/FTB-Chunks#78]
[crash-2020-12-29_16.25.39-server.txt](https://github.com/FTBTeam/FTB-Chunks/files/5751222/crash-2020-12-29_16.25.39-server.txt)
Already contacted mod dev, and told me to post the issue here.

**Comment by Minothor** [comment]
Just encountered the same thing here, in my case with the farmer bee interacting with crops within a claimed chunk:
[message.txt](https://github.com/FTBTeam/FTB-Chunks/files/5761938/message.txt)

**Comment by JaisDK** [comment]
The Famer Bee is calling `ForgeHooks.onRightClickBlock` with a FakePlayer. Looks like ftbchunks does not handle fake players in the permission check.
