### ISSUE TITLE
Question (suggestion?) - FTB Teams

### ISSUE THREAD

**Issue by Flexz9** [FTBTeam/FTB-Chunks#84]
I noticed a suggestion that I 100% would love to see https://github.com/FTBTeam/FTB-Chunks/issues/73

But some players play in teams, and I assume FTB Teams is the solution for that. But then it also needs support that if 1 players of that team is online, all chunks become chunloaded.

Also we give different amount of chunks to claim and load based on time played with ranks. Is teams just a sum of all the players in a team?

**Comment by MaxNeedsSnacks** [comment]
Merging into #112
