### ISSUE TITLE
More of a suggestion than an issue, did not see a discord link to write to you

### ISSUE THREAD

**Issue by celsiusqc** [FTBTeam/FTB-Chunks#85]
If it would be possible to add a item (ex: emerald coin) which would let the player purchase +1 to the possible chunks they can load. They would start with desired server amount of chunks they can claim, and they can "buy" more by using in game resources. Modpack makers could use craftweaker to change the resources needed to make the coin (to decide how hard/easy) they want it to be to buy more. You could also add a config to disable/enable the feature + a config to add a cap to max allowed total chunks they can load with ftb chunks.
I hope you take this into consideration!
Thanks!

**Comment by MaxNeedsSnacks** [comment]
This will not be part of FTB Chunks itself, however you can implement this with KubeJS scripts and commands (`/ftbchunks admin extra_claim_chunks` comes to mind)
