### ISSUE TITLE
Incompatabilities with Create 1.16.4

### ISSUE THREAD

**Issue by JPEGMC** [FTBTeam/FTB-Chunks#90]
Deployers From Create (A Block that interacts with the world) does not work at all in claimed FTBChunks. If you unclaim a chunk using FTBChunks the Deployer block immediately starts working as intended. This issue results in the player not being able to do anything with Deployers inside of claimed Chunks and can severely impact the player's experience due to the fact that their builds using it aren't secure.

**Comment by Martijnpold** [comment]
@JPEGMC This isn't really an issue that should be this mod's responsibility to fix. Besides, Create has it's own dedicated fake player which you can actually add as an ally within FTB-Chunks (both mods add this exactly for this reason). Do some research...

**Comment by JPEGMC** [comment]
I've tried doing some research for a bit now and I'm still unsure if the fake player that you're mentioning should show as my name or as "Deployer" on the fake players list. If i ally myself (My fake player self) contraptions from create still don't work and to add onto this, the only fake players that i see are my friends'

**Comment by Ruchian** [comment]
There exists a mod that makes people's names hidden, causing them to show up as fakeplayers in FTB Chunk's list and Unknown in Vanilla's online player list. If you used any of that, then you may indeed show as a fakeplayer yourself. If it is something seperate from you, then it could be that the specific fakeplayer was made by a tile entity block that is tied to you, which usually means something like being the original creator of the said block or being the owner. (Such block often comes with security.) 
I never played with Create before, but I don't think judging from the mod's theme, that it has advanced security features or links blocks to a player, so in all likelihood it is a different fakeplayer.
If you have multiple of these Deployer Blocks and they are all detected under the same FakePlayer, than that maybe concerning. (it could be a security issue), but this is more for the developer of Create to puzzle with.

Fakeplayers are indicated by their yellow names, if I recall correctly.
If the deployer isn't between the players in the list then, something maybe weird. 
I suppose you feel its too dangerous to for a moment disable the claim of the chunk? xD
I'm not sure what kind of stress you are under, but yeah--... uhm. If you can't add it to your list of exceptions, then it maybe the only working option for you.
Note that if you do add it, other people might become capable of abusing this if the single fakeplayer indeed covers all deployers. (I'm not sure what they are, but if it can cause damage then, your claim protection may not do much.)

**Comment by MaxNeedsSnacks** [comment]
Whitelisting the deployer should work on its own, if other mods add copious amounts of fake players (for whatever reason) that shouldn't be on us
