### ISSUE TITLE
[Suggestion] Hide sneaking & invisible players from maps

### ISSUE THREAD

**Issue by Brawaru** [FTBTeam/FTB-Chunks#93]
There's an open issue requesting to add a feature to hide all the players — #40.

This is a very good suggestion, but also consider hiding everyone even allies (if #40 is implemented) when they're sneaking or under effects of the invisibility potion. Minecraft's behaviour is to hide player's tag when they're sneaking/invisible, so it'd make sense for players to become invisible to minimap too :)

**Comment by Crazydude323** [comment]
Hiding players if they're invisible would also be great, if hiding them while sneaking is added.

**Comment by Brawaru** [comment]
Oh, yes! You're right, I totally forgot about that. Updated the issue :)
