### ISSUE TITLE
fake-players should be auto-allowed. 

### ISSUE THREAD

**Issue by shattyyt** [FTBTeam/FTB-Chunks#98]
so many issues are coming from mods that have fake players that their fake player doesn't work. since the mod can detect fake players, why not auto allow them? this should be a server config option that is defaulted to on.

**Comment by terijaki** [comment]
How does one even manually allow it?

**Comment by MacAttack-UK** [comment]
I would also like this as it took me an age to realise I had to add fake players via the 'Allies' when you go into the map.
