### ISSUE TITLE
How to adjust players land claim number and force loading chunk numbers on direwolf20 1.16.4

### ISSUE THREAD

**Issue by bakedFish** [FTBTeam/FTB-Chunks#99]
I looked everywhere to see where to adjust the number of land claims and forced loaded chunks in the config and at local file. unlike ftbutilities theres no ranks to adjust the numbers for it. are there any other ways like in game to adjust the number?

**Comment by tessnic** [comment]
I figured it out, was looking a while too. Its in your world save data...so for me /saves/MainWorld/data/ftbchunks then I clicked the text file with a bunch of letter (b2255ea157...etc.json) and youll see your username there. change the extra_claim_chunk and the extra_force_load_chunk to whatever to want...like 1000. I just loaded in and everything seems to work.

**Comment by MaxNeedsSnacks** [comment]
While what tessnic suggested is possible, the easier way is to use the server config (for defaults) or the command `/ftbchunks admin extra_claim_chunks` to give more chunks to individual players
